print("-----------------------------------------------------------")
print("-----------------------------------------------------------")
print("               Hey there! I'm GimmeYourLiver               ")
print("           I'm your personal ChatBot and assistant!        ")
print("      ==============================================       ")
print("       You can do !help to get a list of my commands       ")
print("                 Feel free to report bugs                  ")
print(" ||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ")
print("                   I'm Opensourced!                        ")
print("   +                                                +      ")
print("     Lemme gather some basic information about you:        ")
